spring:

  main:
    allow-circular-references: true

  application:
    name: jwtexample
    id: com.sphirye.jwtexample

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: root

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

server:
  port: 3000
  error:
    include-message: always

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 86400